#pragma once

#include <cstddef>
#include <cstdint>
#include <vector>

#include "core/Platform.h"

namespace bw::core {

class DefineTileMaps;

// One finite square binary Map owned by a DefineTileMaps step. Its index and
// dimensions are generated by that owner.
class BW_API TileMap final {
  friend class DefineTileMaps;

  DefineTileMaps* mOwner;
  uint32_t mIndex;
  uint32_t mMapSize;
  uint32_t mCellSize;
  std::vector<uint8_t> mCells;

  TileMap(DefineTileMaps* owner, uint32_t index, uint32_t mapSize,
          uint32_t cellSize);
  [[nodiscard]] size_t cellIndex(uint32_t x, uint32_t y) const;
  void reset(uint32_t index, uint32_t mapSize, uint32_t cellSize);

public:
  [[nodiscard]] uint32_t getIndex() const;
  [[nodiscard]] uint32_t getMapSize() const;
  [[nodiscard]] uint32_t getCellSize() const;
  [[nodiscard]] uint32_t getWidth() const;
  [[nodiscard]] uint32_t getHeight() const;

  [[nodiscard]] int getCell(uint32_t x, uint32_t y) const;
  void setCell(uint32_t x, uint32_t y, int value);
  void toggleCell(uint32_t x, uint32_t y);
};

}  // namespace bw::core
